{
 "title": "Cyberbullying-detection",
 "time": { "from": "now/M", "to": "now/M" },
 "panels": [
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Accuracy Scores",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", current_accuracy_score, reference_accuracy_score FROM metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "F1 Scores",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", current_f1_score, reference_f1_score FROM metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Precision Scores",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", current_precision_score, reference_precision_score FROM metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Recall Scores",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", current_recall_score, reference_recall_score FROM metrics LIMIT 50 "
    }
   ]
  }
 ]
}