source_stream_name = "tweet_events"
output_stream_name = "tweet_classification"
model_bucket = "mlops-zoomcamp-cyberbullying"
lambda_function_local_path = "../deployment/lambda_function.py"
docker_image_local_path = "../deployment/Dockerfile"
ecr_repo_name = "cyberbullying-detection-model"
lambda_function_name = "cyberbullying_detection_lambda"
